import json
import os
import glob

# Script to transform backup JSON into TypeScript constants
# Place your backup JSON (e.g. CLAIN_Full_Backup_...) in the same directory and run: python import_data.py


def generate_ts():
    # 1. Locate the backup JSON
    json_files = glob.glob("*.json")
    # Filter out known non-data files
    data_files = [f for f in json_files if f not in [
        'metadata.json', 'package.json', 'tsconfig.json']]

    if not data_files:
        print("Error: No data JSON files found in current directory.")
        return

    # Use the most recently modified JSON file
    target_json = max(data_files, key=os.path.getmtime)
    print(f"Reading data from: {target_json}")

    try:
        with open(target_json, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        print(f"Error reading JSON: {e}")
        return

    # 2. Extract modules
    # Handling potential case differences from different backup versions
    people = data.get('PEOPLE', data.get('people', []))
    news = data.get('NEWS', data.get('news', []))
    pubs = data.get('PUBLICATIONS', data.get('publications', []))
    projects = data.get('PROJECTS', data.get('projects', []))
    contact = data.get('CONTACT_DEFAULTS', data.get(
        'contact', data.get('CONTACT', {})))

    # 3. Construct the TypeScript file content
    ts_template = f"""import {{ Publication, Person, NewsItem, ContactInfo, Project, EventItem }} from './types';

/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY import_data.py
 * Manual changes will be overwritten if the script is run again.
 */

export const STATIC_DATA = {{
  PEOPLE: {json.dumps(people, indent=2, ensure_ascii=False)} as Person[],
  NEWS: {json.dumps(news, indent=2, ensure_ascii=False)} as NewsItem[],
  PUBLICATIONS: {json.dumps(pubs, indent=2, ensure_ascii=False)} as Publication[],
  PROJECTS: {json.dumps(projects, indent=2, ensure_ascii=False)} as Project[],
  CONTACT: {json.dumps(contact, indent=2, ensure_ascii=False)} as ContactInfo
}};

export const LAB_NAME = "CLAIN";
export const LAB_FULL_NAME = "Center for Language and Information Research";
export const UNIVERSITY_NAME = "Wuhan University";

export const PEOPLE = STATIC_DATA.PEOPLE;
export const NEWS = STATIC_DATA.NEWS;
export const PUBLICATIONS = STATIC_DATA.PUBLICATIONS;
export const PROJECTS = STATIC_DATA.PROJECTS;
export const CONTACT_DEFAULTS = STATIC_DATA.CONTACT;
export const EVENTS: EventItem[] = [];
"""

    # 4. Write to constants.ts
    try:
        with open('constants.ts', 'w', encoding='utf-8') as f:
            f.write(ts_template)
        print("Successfully updated constants.ts!")
    except Exception as e:
        print(f"Error writing constants.ts: {e}")


if __name__ == "__main__":
    generate_ts()
